sudo : required

services :
  - docker
  - docker-compose
before_install :
  -docker-compose up --build

after_success :
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password=stdin
  -docker tag africabaobab_php-env:latest bayord/africabaobab_php-env
  -docker tag mysql:latest bayord/mysql
  -docker tag phpmyadmin:latest bayord/phpmyadmin
  -docker push bayord/africabaobab_php-env 
  -docker push bayord/mysql
  -docker push bayord/phpmyadmin
